name: CLA Assistant Lite

permissions:
  contents: read
  packages: read

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - uses: cla-assistant/github-action@v2
        with:
          repo-token: ${{ secrets.CLA_ASSISTANT_TOKEN }}
          path-to-cla: 'CLA.md'
