name: Security Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run
        run: semgrep scan --config p/owasp-top-ten --serif --output semgrep.sarif

      - name: Upload
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
    
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
